
INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,781,'24_2',1)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,1153,'24_2',2)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,1151,'24_2',3)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,1221,'24_2',4)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,577,'24_2',5)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,519,'24_2',6)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,520,'24_2',7)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,521,'24_2',8)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,522,'24_2',9)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,523,'24_2',10)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,731,'24_2',11)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,734,'24_2',12)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,736,'24_2',13)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,738,'24_2',14)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,740,'24_2',15)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,380,'24_1',1)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,739,'24_1',2)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,737,'24_1',3)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,735,'24_1',4)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,733,'24_1',5)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,732,'24_1',6)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,507,'24_1',7)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,508,'24_1',8)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,509,'24_1',9)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,510,'24_1',10)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,511,'24_1',11)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,512,'24_1',12)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,1147,'24_1',13)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,1220,'24_1',14)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,1150,'24_1',15)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,1152,'24_1',16)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,781,'24_1',17)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,760,'6_1',1)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,586,'6_1',2)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,587,'6_1',3)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,588,'6_1',4)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,733,'6_1',5)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,732,'6_1',6)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,507,'6_1',7)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,508,'6_1',8)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,509,'6_1',9)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,510,'6_1',10)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,511,'6_1',11)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,512,'6_1',12)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,513,'6_1',13)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,514,'6_1',14)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,16,'6_2',1)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,516,'6_2',2)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,517,'6_2',3)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,577,'6_2',4)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,519,'6_2',5)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,520,'6_2',6)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,521,'6_2',7)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,522,'6_2',8)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,523,'6_2',9)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,731,'6_2',10)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,734,'6_2',11)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,761,'6_2',12)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,596,'6_2',13)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,597,'6_2',14)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,760,'6_2',15)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,588,'7_1',1)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,733,'7_1',2)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,732,'7_1',3)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,507,'7_1',4)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,508,'7_1',5)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,509,'7_1',6)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,510,'7_1',7)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,511,'7_1',8)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,512,'7_1',9)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,513,'7_1',10)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,514,'7_1',11)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,16,'7_1',12)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,16,'7_2',1)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,516,'7_2',2)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,517,'7_2',3)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,577,'7_2',4)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,519,'7_2',5)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,520,'7_2',6)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,521,'7_2',7)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,522,'7_2',8)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,523,'7_2',9)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,731,'7_2',10)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,734,'7_2',11)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,761,'7_2',12)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,381,'35_1',1)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,589,'35_1',2)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,660,'35_1',3)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,585,'35_1',4)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,1020,'35_1',5)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,791,'35_1',6)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,792,'35_1',7)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,730,'35_1',8)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,568,'35_1',9)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,300,'35_2',1)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,563,'35_2',2)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,845,'35_2',3)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,1022,'35_2',4)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,1021,'35_2',5)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,360,'35_2',6)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,661,'35_2',7)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,592,'35_2',8)
/

INSERT INTO STATION_BUS (ID, STATION_ID,BUS_ID,STATION_ORDER) VALUES (S_STATION_BUS.NEXTVAL,381,'35_2',9)
/

